/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Braian
 */
public class elegirTablero extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form elegirTablero
     */
    nodo nodoUsuarios;
    nodoPlanta catalogoPlanta;
    nodoZombie catalogoZombie;

    public elegirTablero(nodo nodoUsuarios, nodoPlanta catalogoPlanta, nodoZombie catalogoZombie) {
        this.nodoUsuarios = nodoUsuarios;
        this.catalogoPlanta = catalogoPlanta;
        this.catalogoZombie = catalogoZombie;
        initComponents();
        fondoElegirTablero jpanel = new fondoElegirTablero();
        this.add(jpanel, BorderLayout.CENTER);

        this.setTitle("Elegir tablero de juego");

        this.setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setSize(806, 420);
        instanciar();
    }

    public void instanciar() {
        btnsiguiente.addActionListener(this);
        btnsiguiente.setText("                                                       ");
        btnsiguiente.setOpaque(false);
        btnsiguiente.setContentAreaFilled(false);
        btnsiguiente.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        btnsiguiente = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        buttonGroup1.add(rb1);
        rb1.setText("Tablero 4X8");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setLabel("Tablero 5X8");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setToolTipText("");
        rb3.setLabel("Tablero 6X8");

        buttonGroup1.add(rb4);
        rb4.setToolTipText("");
        rb4.setLabel("Tablero 7X8");

        buttonGroup1.add(rb5);
        rb5.setLabel("Tablero 8X8");

        buttonGroup1.add(rb6);
        rb6.setLabel("Tablero 9X8");

        btnsiguiente.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 532, Short.MAX_VALUE)
                .addComponent(btnsiguiente)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb3)
                    .addComponent(rb5)
                    .addComponent(rb1))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb6)
                            .addComponent(rb4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3)
                    .addComponent(rb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb5)
                    .addComponent(rb6))
                .addGap(22, 22, 22)
                .addComponent(btnsiguiente)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elegirTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elegirTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elegirTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elegirTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elegirTablero(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnsiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == btnsiguiente) {
            tableroPrincipal frame;
            if (rb1.isSelected()) {
                System.out.println("pantalla 4x8");
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 4, 8);
                frame.setVisible(true);
                this.setVisible(false);

            } else if (rb2.isSelected()) {
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 5, 8);
                frame.setVisible(true);
                this.setVisible(false);
            } else if (rb3.isSelected()) {
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 6, 8);
                frame.setVisible(true);
                this.setVisible(false);
            } else if (rb4.isSelected()) {
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 7, 8);
                frame.setVisible(true);
                this.setVisible(false);
            } else if (rb5.isSelected()) {
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 8, 8);
                frame.setVisible(true);
                this.setVisible(false);
            } else if (rb6.isSelected()) {
                frame = new tableroPrincipal(nodoUsuarios, catalogoPlanta, catalogoZombie, 9, 8);
                frame.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Debe escoger un tablero para continuar.");
            }
        }
    }
}
