/*
 * PnlFondo.java
 *
 * Created on 19 de julio de 2007, 07:56 PM
 */
package codigo;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Jorge
 */
public class PnlFondo extends javax.swing.JPanel implements ActionListener {

    private JFrame jFramePadre;
    public JButton iniciar;
    FrmPrincipal obj;
    /**
     * Creates new form PnlFondo
     */
    public PnlFondo(FrmPrincipal aux) {
        initComponents();
        initComponents2();
        this.setSize(1200, 700);
        obj = aux;

    }

    public void initComponents2() {
        iniciar = new JButton();
        iniciar.addActionListener(this);
        iniciar.setText("                                                       ");
        iniciar.setOpaque(false);
        iniciar.setContentAreaFilled(false);
        iniciar.setBorderPainted(false);

        iniciar.setBounds(490, 545, 200, 25);

    }

    @Override
    public void paintComponent(Graphics g) {
        
        Dimension tamanio = getSize();
        ImageIcon imagenFondo = new ImageIcon(getClass().
                getResource("/imagenes/FondoZombi.png"));
        g.drawImage(imagenFondo.getImage(), 0, 0,
                tamanio.width, tamanio.height, null);
        setOpaque(false);

        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jFramePadre
     */
    public JFrame getjFramePadre() {
        return jFramePadre;
    }

    /**
     * @param jFramePadre the jFramePadre to set
     */
    public void setjFramePadre(JFrame jFramePadre) {

        this.jFramePadre = jFramePadre;
        this.jFramePadre.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //this.jFramePadre.setLocationRelativeTo(null);
                
        this.jFramePadre.add(iniciar);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
    if(e.getSource()==iniciar){
        usuariosMenu menu = new usuariosMenu();


        

        //this.pack();
        
        menu.setVisible(true);
        
        obj.setVisible(false);
        System.out.println("Iniciar Juego");
    }
    
    }

}
