/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Braian
 */
public class tableroPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form tableroPrincipal
     */
    nodo nodoUsuarios;
    nodoPlanta catalogoPlanta;
    nodoZombie catalogoZombie;
    String nJugador1;
    String nJugador2;
    int contador1;
    int contador2;
    matrizEstrucutas EDDCola;
    matrizEstrucutas EDDPila;

    public tableroPrincipal(nodo nodoUsuarios, nodoPlanta catalogoPlanta, nodoZombie catalogoZombie) {
        this.nodoUsuarios = nodoUsuarios;
        this.catalogoPlanta = catalogoPlanta;
        this.catalogoZombie = catalogoZombie;
        nodo usuario = nodoUsuarios;
        //Jugador uno
        nJugador1 = usuario.Nombre;
        contador1 = usuario.cantidad;

        nJugador2 = usuario.sig.Nombre;
        contador2 = usuario.sig.cantidad;

        EDDCola = new matrizEstrucutas(contador1);
        EDDPila = new matrizEstrucutas(contador2);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        initComponents();
        agregarDatos();

        //this.setResizable(false);
        // this.setSize(1200, 700);
    }
    int random;
public void elegirRamdon(int catagolo){
random = (int) (Math.random() * catagolo + 1);



}
    public void agregarDatos() {

        lblNombreP.setText(nJugador1);

        lblContadorP.setText(String.valueOf(contador1));
        //Jugador dos

        lblNombreP1.setText(nJugador2);
        lblContadorP1.setText(String.valueOf(contador2));

        EDDCola.setBounds(15, 20, 150, 400);
        EDDCola.setBackground(Color.RED);
        EDDCola.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, null, null, null, null));
        pnlPlantas.add(EDDCola);

        EDDPila.setBounds(15, 20, 150, 400);
        EDDPila.setBackground(Color.RED);
        EDDPila.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, null, null, null, null));
        pnlZombie.add(EDDPila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        txtnombreP = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        txtDisponibleP = new javax.swing.JLabel();
        lblContadorP = new javax.swing.JLabel();
        pnlPlantas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDatos2 = new javax.swing.JPanel();
        txtnombreP1 = new javax.swing.JLabel();
        lblNombreP1 = new javax.swing.JLabel();
        txtDisponibleP1 = new javax.swing.JLabel();
        lblContadorP1 = new javax.swing.JLabel();
        pnlZombie = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenArchivo = new javax.swing.JMenu();
        JmunIteSlr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        pnlDatos.setBackground(new java.awt.Color(153, 0, 0));
        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Jugador"));
        pnlDatos.setPreferredSize(new java.awt.Dimension(200, 100));

        txtnombreP.setText("Nombre:");

        lblNombreP.setText("jLabel1");

        txtDisponibleP.setText("Plantas Disponibles:");

        lblContadorP.setText("jLabel1");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(txtnombreP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(txtDisponibleP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContadorP)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombreP)
                    .addComponent(lblNombreP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisponibleP)
                    .addComponent(lblContadorP)))
        );

        pnlPlantas.setBackground(new java.awt.Color(0, 153, 51));
        pnlPlantas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlPlantas.setPreferredSize(new java.awt.Dimension(200, 578));

        javax.swing.GroupLayout pnlPlantasLayout = new javax.swing.GroupLayout(pnlPlantas);
        pnlPlantas.setLayout(pnlPlantasLayout);
        pnlPlantasLayout.setHorizontalGroup(
            pnlPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        pnlPlantasLayout.setVerticalGroup(
            pnlPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPrincipal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(861, 581));
        jLabel1.setPreferredSize(new java.awt.Dimension(861, 581));

        pnlDatos2.setBackground(new java.awt.Color(153, 0, 0));
        pnlDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Jugador"));
        pnlDatos2.setPreferredSize(new java.awt.Dimension(200, 100));

        txtnombreP1.setText("Nombre:");

        lblNombreP1.setText("jLabel1");

        txtDisponibleP1.setText("Plantas Disponibles:");

        lblContadorP1.setText("jLabel1");

        javax.swing.GroupLayout pnlDatos2Layout = new javax.swing.GroupLayout(pnlDatos2);
        pnlDatos2.setLayout(pnlDatos2Layout);
        pnlDatos2Layout.setHorizontalGroup(
            pnlDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatos2Layout.createSequentialGroup()
                        .addComponent(txtnombreP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreP1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatos2Layout.createSequentialGroup()
                        .addComponent(txtDisponibleP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContadorP1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDatos2Layout.setVerticalGroup(
            pnlDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatos2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombreP1)
                    .addComponent(lblNombreP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisponibleP1)
                    .addComponent(lblContadorP1)))
        );

        pnlZombie.setBackground(new java.awt.Color(0, 153, 51));
        pnlZombie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlZombie.setPreferredSize(new java.awt.Dimension(200, 578));

        javax.swing.GroupLayout pnlZombieLayout = new javax.swing.GroupLayout(pnlZombie);
        pnlZombie.setLayout(pnlZombieLayout);
        pnlZombieLayout.setHorizontalGroup(
            pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        pnlZombieLayout.setVerticalGroup(
            pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jmenArchivo.setText("Archivo");

        JmunIteSlr.setText("Salir");
        JmunIteSlr.setActionCommand("");
        jmenArchivo.add(JmunIteSlr);

        jMenuBar1.add(jmenArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableroPrincipal(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmunIteSlr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmenArchivo;
    private javax.swing.JLabel lblContadorP;
    private javax.swing.JLabel lblContadorP1;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblNombreP1;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatos2;
    private javax.swing.JPanel pnlPlantas;
    private javax.swing.JPanel pnlZombie;
    private javax.swing.JLabel txtDisponibleP;
    private javax.swing.JLabel txtDisponibleP1;
    private javax.swing.JLabel txtnombreP;
    private javax.swing.JLabel txtnombreP1;
    // End of variables declaration//GEN-END:variables
}
